<?php
/**
 * Created by PhpStorm.
 * User: vanch3d <nicolas.github@calques3d.org>
 * Date: 03/02/2018
 * Time: 18:25
 */

namespace NVL;

use NVL\Controllers\APIController;
use Slim\Http\Request;
use Slim\Http\Response;
use Swagger\Annotations as OAS;

/**
 * Class SwaggerAPI
 * @see https://gist.github.com/vanch3d/fce679e6ab9f6877a27d7a21c5170aa9
 */
class SwaggerAPI extends APIController
{
    /**
     * @OAS\Get(
     *     path="/projects",
     *     summary="Get the list of all projects in the application",
     *     tags={"Project"},
     *     description="",
     *     operationId="getAllProjects",
     *     @OAS\Parameter(
     *          ref="#/components/parameters/API_output",
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="successful operation",
     *          @OAS\MediaType(
     *              mediaType="application/json",
     *              @OAS\Schema(
     *                  @OAS\Property(
     *                      property="data",
     *                      type="array",
     *                      @OAS\Items(
     *                          ref="#/components/schemas/Project"
     *                      ),
     *                  ),
     *                  @OAS\Property(property="metadata",type="object"),
     *                  @OAS\Property(property="errors",type="array"),
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=500,
     *         description="cannot generate the list",
     *     ),
     * )
     */
    public function getAllProjects(Request $request, Response $response, array $args)
    {
        return parent::getAllProjects($request, $response, $args); // TODO: Change the autogenerated stub
    }

    /**
     * @OAS\Get(
     *     path="/publications",
     *     summary="Get the list of all publications",
     *     tags={"Publication"},
     *     description="",
     *     operationId="getAllPublications",
     *     @OAS\Parameter(
     *          ref="#/components/parameters/API_output",
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="successful operation",
     *          @OAS\MediaType(
     *              mediaType="application/json",
     *              @OAS\Schema(
     *                  @OAS\Property(
     *                      property="data",
     *                      type="array",
     *                      @OAS\Items(
     *                          ref="#/components/schemas/Publication"
     *                      ),
     *                  ),
     *                  @OAS\Property(property="metadata",type="object"),
     *                  @OAS\Property(property="errors",type="array"),
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=500,
     *         description="cannot generate the list",
     *     ),
     * )
     */
    public function getAllPublications(Request $request, Response $response, array $args)
    {
        return parent::getAllPublications($request, $response, $args); // TODO: Change the autogenerated stub
    }

    /**
     * @OAS\Get(
     *     path="/projects/{name}",
     *     summary="Get the project specified by its id",
     *     tags={"Project"},
     *     description="Return a single project",
     *     operationId="getProject",
     *     @OAS\Parameter(
     *          ref="#/components/parameters/Project_id"
     *     ),
     *     @OAS\Parameter(
     *          ref="#/components/parameters/API_output"
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="successful operation",
     *          @OAS\MediaType(
     *              mediaType="application/json",
     *              @OAS\Schema(
     *                  @OAS\Property(
     *                      property="data",
     *                      type="object",
     *                      ref="#/components/schemas/Project"
     *                  ),
     *                  @OAS\Property(property="metadata",type="object"),
     *                  @OAS\Property(property="errors",type="array"),
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=404,
     *         description="the project specified by 'id' does not exist",
     *     ),
     * )
     */
    public function getProject(Request $request, Response $response, array $args)
    {
        return parent::getProject($request, $response, $args); // TODO: Change the autogenerated stub
    }

    /**
     * @OAS\Get(
     *     path="/projects/{name}/publications",
     *     summary="Get the publications associated with the project specified by its id",
     *     tags={"Project"},
     *     description="",
     *     operationId="getPublications",
     *     @OAS\Parameter(
     *          ref="#/components/parameters/Project_id"
     *     ),
     *     @OAS\Parameter(
     *          ref="#/components/parameters/API_output"
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="successful operation",
     *          @OAS\MediaType(
     *              mediaType="application/json",
     *              @OAS\Schema(
     *                  @OAS\Property(
     *                      property="data",
     *                      type="array",
     *                      @OAS\Items(
     *                          ref="#/components/schemas/Publication"
     *                      ),
     *                  ),
     *                  @OAS\Property(property="metadata",type="object"),
     *                  @OAS\Property(property="errors",type="array"),
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=404,
     *         description="the project specified by 'id' does not exist",
     *     ),
     * )
     */
    public function getPublications(Request $request, Response $response, array $args)
    {
        return parent::getPublications($request, $response, $args); // TODO: Change the autogenerated stub
    }

    /**
     * @OAS\Get(
     *     path="/projects/{name}/slides",
     *     summary="Get the slides associated with the project specified by its id",
     *     tags={"Project"},
     *     description="",
     *     operationId="getSlides",
     *     @OAS\Parameter(
     *          ref="#/components/parameters/Project_id"
     *     ),
     *     @OAS\Parameter(
     *          ref="#/components/parameters/API_output"
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="successful operation",
     *          @OAS\MediaType(
     *              mediaType="application/json",
     *              @OAS\Schema(
     *                  @OAS\Property(
     *                      property="data",
     *                      type="array",
     *                      @OAS\Items(
     *                          ref="#/components/schemas/Slide"
     *                      ),
     *                  ),
     *                  @OAS\Property(property="metadata",type="object"),
     *                  @OAS\Property(property="errors",type="array"),
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=404,
     *         description="the project specified by 'id' does not exist",
     *     ),
     * )
     */
    public function getSlides(Request $request, Response $response, array $args)
    {
        return parent::getSlides($request, $response, $args);
    }


    /**
     * @OAS\Get(
     *     path="/projects/{name}/images",
     *     summary="Get the images associated with the project specified by its id",
     *     tags={"Project"},
     *     description="",
     *     operationId="getImages",
     *     @OAS\Parameter(
     *          ref="#/components/parameters/Project_id"
     *     ),
     *     @OAS\Parameter(
     *          ref="#/components/parameters/API_output"
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="successful operation",
     *          @OAS\MediaType(
     *              mediaType="application/json",
     *              @OAS\Schema(
     *                  @OAS\Property(
     *                      property="data",
     *                      type="array",
     *                      @OAS\Items(
     *                          ref="#/components/schemas/Image"
     *                      ),
     *                  ),
     *                  @OAS\Property(property="metadata",type="object"),
     *                  @OAS\Property(property="errors",type="array"),
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=404,
     *         description="the project specified by 'id' does not exist",
     *     ),
     * )
     */
    public function getImages(Request $request, Response $response, array $args)
    {
        return parent::getImages($request, $response, $args); // TODO: Change the autogenerated stub
    }


    /**
     * @OAS\Get(
     *     path="/projects/{name}/repos",
     *     summary="Get information about the GitHub repositories associated with the project specified by its id",
     *     tags={"Project"},
     *     description="",
     *     operationId="getRepositories",
     *     @OAS\Parameter(
     *          ref="#/components/parameters/Project_id"
     *     ),
     *     @OAS\Parameter(
     *          ref="#/components/parameters/API_output"
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="successful operation",
     *          @OAS\MediaType(
     *              mediaType="application/json",
     *              @OAS\Schema(
     *                  @OAS\Property(
     *                      property="data",
     *                      type="array",
     *                      @OAS\Items(
     *                          ref="#/components/schemas/Contribution"
     *                      ),
     *                  ),
     *                  @OAS\Property(
     *                      property="metadata",
     *                      type="object",
     *                      @OAS\Property(
     *                          property="author",
     *                          type="object",
     *                          ref="#/components/schemas/Author"
     *                      ),
     *                  ),
     *                  @OAS\Property(
     *                      property="errors",
     *                      type="array",
     *                      @OAS\Items(
     *                          ref="#/components/schemas/Error"
     *                      ),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=404,
     *         description="the project specified by 'id' does not exist",
     *     ),
     * )
     */
    public function getRepositories(Request $request, Response $response, array $args)
    {
        return parent::getRepositories($request, $response, $args); // TODO: Change the autogenerated stub
    }


}

