<?php
/**
 * Created by PhpStorm.
 * User: vanch3d <nicolas.github@calques3d.org>
 * Date: 07/03/2018
 * Time: 13:28
 */

namespace NVL;

use NVL\Controllers\APIController;
use Slim\Http\Request;
use Slim\Http\Response;
use Swagger\Annotations as OAS;

class UNAPIController extends APIController
{
    /**
     * @OAS\Get(
     *     path="/unapi",
     *     summary="Base of the unAPI service",
     *     tags={"unAPI"},
     *     description="",
     *     operationId="unAPI",
     *     @OAS\Parameter(
     *          name="id",
     *          in="query",
     *          description="the unique id of the publication to be retrieved",
     *          required=false,
     *          @OAS\Schema(
     *              type="string"
     *          ),
     *     ),
     *     @OAS\Parameter(
     *          name="format",
     *          in="query",
     *          description="the format of the publication record to be retrieved",
     *          required=false,
     *          @OAS\Schema(
     *              type="string"
     *          )
     *     ),
     *     @OAS\Response(
     *          response=200,
     *          description="no parameters in query; return the list of all supported formats",
     *          @OAS\MediaType(
     *              mediaType="application/xml",
     *              @OAS\Schema(
     *                  ref="#/components/schemas/AllFormats"
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *          response=404,
     *          description="bad request: the id is missing or not recognised",
     *          @OAS\MediaType(
     *              mediaType="application/xml",
     *              @OAS\Schema(
     *                  type="object",
     *                  @OAS\Xml( name= "nvl-slim-api" ),
     *                  @OAS\Property(
     *                      property="version",
     *                      type="string",
     *                      @OAS\Xml( attribute=true ),
     *                      example="0.3",
     *                  ),
     *                  @OAS\Property(
     *                      property="error",
     *                      type="array",
     *                        ref="#/components/schemas/Error",
     *                  )
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *          response=300,
     *          description="format is missing; return a list of supported formats",
     *          @OAS\MediaType(
     *              mediaType="application/xml",
     *              @OAS\Schema(
     *                  ref="#/components/schemas/PublicationFormats"
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=406,
     *         description="bad request; the format is not recognised",
     *          @OAS\MediaType(
     *              mediaType="application/xml",
     *              @OAS\Schema(
     *                  type="object",
     *                  @OAS\Xml( name= "nvl-slim-api" ),
     *                  @OAS\Property(
     *                      property="version",
     *                      type="string",
     *                      @OAS\Xml( attribute=true ),
     *                      example="0.3",
     *                  ),
     *                  @OAS\Property(
     *                      property="error",
     *                      type="array",
     *                        ref="#/components/schemas/Error",
     *                  )
     *              ),
     *          ),
     *     ),
     *     @OAS\Response(
     *         response=302,
     *         description="operation successful; redirect to the publication record in the given format",
     *          @OAS\MediaType(
     *              mediaType="application/xml",
     *              @OAS\Schema(
     *                  type="object",
     *                  @OAS\Xml( name= "nvl-slim-api" ),
     *                  @OAS\Property(
     *                      property="version",
     *                      type="string",
     *                      @OAS\Xml( attribute=true ),
     *                      example="0.3",
     *                  ),
     *                  @OAS\Property(
     *                      property="error",
     *                      type="array",
     *                        ref="#/components/schemas/Error",
     *                  )
     *              ),
     *          ),
     *     )
     * )
     */
    public function unAPI(Request $request, Response $response)
    {
        return parent::unAPI($request, $response); // TODO: Change the autogenerated stub
    }

}